apiVersion: v1
kind: ConfigMap
metadata:
    name: scripts-cm
data:
    locustfile.py: |
        import time
        from locust import HttpUser, task, constant

        class QuickstartUser(HttpUser):
            @task
            def main(self):
                self.client.get("/socketio")

            wait_time = constant(1)
