apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    import time
    from locust import HttpUser, task, constant
    from locust_plugins.users.socketio import SocketIOUser

    class QuickstartUser(HttpUser):
        @task
        def socketio(self):
            self.client.get("/socketio")

        wait_time = constant(1)
