apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: locust-worker
    app: locust-worker
  name: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      role: locust-worker
      app: locust-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-worker
        app: locust-worker
    spec:
      containers:
        - image: locustio/locust:latest
          imagePullPolicy: Always
          name: worker
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install locust-plugins 'locust-plugins[websocket]' && \
              locust --worker --master-host=locust-master
          volumeMounts:
            - mountPath: /home/locust
              name: locust-scripts
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: locust-scripts
          configMap:
            name: scripts-cm
      nodeSelector:
        karpenter.sh/nodepool: default-arm64
