apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
    name: web-app
    namespace: example
spec:
    parentRefs:
        - name: example-network
          sectionName: tls-with-default-domain
    rules:
        - backendRefs:
              - name: web-app
                kind: Service
                port: 8000
                namespace: example
          matches:
              - path:
                    type: PathPrefix
                    value: /
